--- #YAML:1.0
name:               FCGI-Restarter
version:            0.12
abstract:           Restart FCGI process on the fly
author:
    - Grishaev Anatoliy  <grian@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Tiny:  0.10
    FCGI:                 0.67
    perl:                 5.008001
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
